# Generated by Django 2.2.4 on 2022-09-29 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restful_tv_shows_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='show',
            managers=[
            ],
        ),
        migrations.RenameField(
            model_name='show',
            old_name='tiltle',
            new_name='title',
        ),
    ]
